# Weighted K-Nearest Neighbor (WKNN)

Notebook ini membahas algoritma **Weighted K-Nearest Neighbor (WKNN)** yang merupakan pengembangan dari algoritma **K-Nearest Neighbor (KNN)**.

Materi yang dibahas:

1. Pengertian Weighted KNN
2. Konsep dasar WKNN
3. Rumus Euclidean Distance
4. Rumus bobot WKNN
5. Voting berbobot
6. Contoh kasus menggunakan dataset harga rumah
7. Perhitungan manual WKNN
8. Implementasi WKNN menggunakan Python

## 1. Pengertian WKNN

Weighted K-Nearest Neighbor (WKNN) adalah metode klasifikasi yang merupakan pengembangan dari algoritma **K-Nearest Neighbor (KNN)**.

Perbedaan utama antara **KNN** dan **WKNN** adalah cara menentukan pengaruh setiap tetangga.

- Pada **KNN**, semua tetangga memiliki pengaruh yang sama.
- Pada **WKNN**, setiap tetangga diberikan **bobot berdasarkan jaraknya** terhadap data uji.

Semakin dekat jarak suatu data terhadap data uji, maka bobotnya akan semakin besar.

## 2. Konsep Dasar WKNN

Algoritma WKNN bekerja berdasarkan asumsi bahwa data yang memiliki karakteristik mirip akan berada pada jarak yang berdekatan.

Langkah utama WKNN:

1. Menentukan nilai **K**.
2. Menghitung jarak antara data uji dan seluruh data latih.
3. Mengurutkan jarak dari yang terkecil.
4. Mengambil **K tetangga terdekat**.
5. Menghitung bobot setiap tetangga.
6. Melakukan **voting berbobot**.
7. Memilih kelas dengan total bobot terbesar.

## 3. Euclidean Distance

Euclidean Distance digunakan untuk menghitung jarak antara dua data.

### Rumus

$$
d(x,y) = \sqrt{\sum_{i=1}^{n}(x_i - y_i)^2}
$$

Keterangan:

- $d(x,y)$ = jarak antara dua data
- $x_i$ = nilai atribut pada data uji
- $y_i$ = nilai atribut pada data latih

## 4. Rumus Bobot WKNN

Setelah jarak dihitung, setiap tetangga diberikan bobot menggunakan rumus:

$$
w_i = \frac{1}{d_i}
$$

Keterangan:

- $w_i$ = bobot tetangga ke-i
- $d_i$ = jarak tetangga ke-i

Semakin kecil jarak, maka bobot yang dihasilkan semakin besar.

## 5. Voting Berbobot

Setelah bobot setiap tetangga dihitung, langkah berikutnya adalah melakukan voting berbobot.

Rumus:

$$
V_j = \sum w_i
$$

dimana $V_j$ adalah total bobot untuk kelas ke-j.

## Dataset Harga Rumah

| Rumah | Luas_Tanah | Luas_Bangunan | Kamar | Harga |
|------|------|------|------|------|
| R1 | 120 | 90 | 3 | Murah |
| R2 | 200 | 150 | 4 | Mahal |
| R3 | 150 | 110 | 3 | Murah |
| R4 | 90 | 70 | 2 | Murah |
| R5 | 140 | 100 | 3 | ? |

Data **R5** adalah **data uji** yang ingin diprediksi kelas harganya.

## Perhitungan Euclidean Distance

Contoh perhitungan jarak antara **R5** dan **R1**:

$$
d = \sqrt{(140-120)^2 + (100-90)^2 + (3-3)^2}
$$

$$
d = \sqrt{400 + 100 + 0}
$$

$$
d = 22.36
$$

In [1]:
import pandas as pd

data = {
'Rumah':['R1','R2','R3','R4'],
'Luas_Tanah':[120,200,150,90],
'Luas_Bangunan':[90,150,110,70],
'Kamar':[3,4,3,2],
'Harga':['Murah','Mahal','Murah','Murah']
}

df = pd.DataFrame(data)
df

  Rumah  Luas_Tanah  Luas_Bangunan  Kamar  Harga
0    R1         120             90      3  Murah
1    R2         200            150      4  Mahal
2    R3         150            110      3  Murah
3    R4          90             70      2  Murah

In [2]:
import numpy as np

target = np.array([140,100,3])

features = df[['Luas_Tanah','Luas_Bangunan','Kamar']].values

distances = np.sqrt(((features-target)**2).sum(axis=1))

df['Distance'] = distances

df.sort_values('Distance')

  Rumah  Luas_Tanah  Luas_Bangunan  Kamar  Harga   Distance
2    R3         150            110      3  Murah  14.142136
0    R1         120             90      3  Murah  22.360680
3    R4          90             70      2  Murah  58.318093
1    R2         200            150      4  Mahal  78.108898

## Menentukan K

Misalkan dipilih **K = 3** tetangga terdekat.

In [3]:
k = 3

nearest = df.sort_values('Distance').head(k)

nearest

  Rumah  Luas_Tanah  Luas_Bangunan  Kamar  Harga   Distance
2    R3         150            110      3  Murah  14.142136
0    R1         120             90      3  Murah  22.360680
3    R4          90             70      2  Murah  58.318093

## Menghitung Bobot

Bobot dihitung menggunakan rumus:

$$
w = \frac{1}{d}
$$

In [4]:
nearest['Weight'] = 1 / nearest['Distance']

nearest

  Rumah  Luas_Tanah  Luas_Bangunan  Kamar  Harga   Distance    Weight
2    R3         150            110      3  Murah  14.142136  0.070711
0    R1         120             90      3  Murah  22.360680  0.044721
3    R4          90             70      2  Murah  58.318093  0.017147

## Voting Berbobot

Total bobot untuk setiap kelas dihitung.

In [5]:
nearest.groupby('Harga')['Weight'].sum()

Harga
Murah    0.132579
Name: Weight, dtype: float64

## Kesimpulan

Dengan menggunakan metode **Weighted K-Nearest Neighbor**, kelas harga rumah R5 dapat diprediksi berdasarkan tetangga yang paling dekat.

Metode WKNN memberikan bobot yang lebih besar pada data yang memiliki jarak lebih dekat terhadap data uji sehingga hasil prediksi menjadi lebih akurat dibandingkan metode KNN biasa.