# K-Nearest Neighbor (KNN) dan KNN Imputation

Notebook ini membahas algoritma **K-Nearest Neighbor (KNN)** serta penerapannya untuk **mengisi missing value** pada dataset.

Materi yang dibahas:

1. Konsep dasar K-Nearest Neighbor
2. Cara kerja algoritma KNN
3. Euclidean Distance
4. Missing Value pada data
5. KNN Imputation
6. Contoh kasus menggunakan dataset harga rumah
7. Perhitungan jarak secara manual
8. Implementasi menggunakan Python

## 1. K-Nearest Neighbor (KNN)

K-Nearest Neighbor (KNN) merupakan salah satu algoritma dalam **machine learning** yang digunakan untuk melakukan **klasifikasi maupun regresi**.

Algoritma ini bekerja berdasarkan prinsip **kedekatan antar data**. Suatu data baru akan diprediksi nilainya dengan melihat data lain yang memiliki karakteristik paling mirip.

Konsep utama KNN adalah:

- Data yang **mirip** cenderung memiliki nilai atau kelas yang **mirip**.
- Tingkat kemiripan antar data diukur menggunakan **jarak (distance)**.

Huruf **K** dalam KNN menunjukkan jumlah tetangga terdekat yang digunakan dalam proses pengambilan keputusan.

## 2. Cara Kerja Algoritma KNN

Langkah kerja algoritma KNN secara umum adalah:

1. Menentukan nilai **K** (jumlah tetangga terdekat).
2. Menghitung jarak antara data yang akan diprediksi dengan seluruh data dalam dataset.
3. Mengurutkan jarak dari yang paling kecil.
4. Memilih **K data dengan jarak paling kecil**.
5. Menentukan hasil prediksi:

- Pada **klasifikasi**, digunakan metode voting.
- Pada **regresi**, digunakan rata-rata nilai dari K tetangga.

## 3. Euclidean Distance

Salah satu metode yang paling umum digunakan untuk menghitung jarak dalam KNN adalah **Euclidean Distance**.

Euclidean Distance menghitung jarak garis lurus antara dua titik dalam ruang multidimensi.

### Rumus Euclidean Distance

$$
d(p,q) = \sqrt{\sum_{i=1}^{n}(p_i - q_i)^2}
$$

Keterangan:

- $d(p,q)$ = jarak antara data $p$ dan $q$
- $p_i$ = nilai atribut ke-i pada data $p$
- $q_i$ = nilai atribut ke-i pada data $q$
- $n$ = jumlah atribut

Semakin kecil nilai jarak, maka semakin tinggi tingkat kemiripan antara dua data.

## 4. Missing Value

Missing value adalah kondisi dimana suatu atribut dalam dataset tidak memiliki nilai.

Missing value dapat disebabkan oleh beberapa faktor:

- kesalahan pencatatan data
- data tidak lengkap
- kesalahan proses pengumpulan data

Jika tidak ditangani dengan baik, missing value dapat mempengaruhi hasil analisis dan performa model.

## 5. KNN Imputation

KNN Imputation adalah metode untuk **mengisi missing value menggunakan konsep KNN**.

Langkah-langkahnya:

1. Mengidentifikasi data yang memiliki missing value.
2. Menghitung jarak antara data tersebut dengan data lain.
3. Mengurutkan jarak dari yang terkecil.
4. Memilih **K tetangga terdekat**.
5. Menghitung nilai estimasi menggunakan **rata-rata nilai dari tetangga terdekat**.

## Dataset Harga Rumah

Dataset berikut menggambarkan karakteristik beberapa rumah.

| Rumah | Luas_Tanah | Luas_Bangunan | Jumlah_Kamar | Harga |
|------|------|------|------|------|
| R1 | 120 | 90 | 3 | 850 |
| R2 | 200 | 150 | 4 | 1500 |
| R3 | 150 | 110 | 3 | 1000 |
| R4 | 90 | 70 | 2 | 600 |
| R5 | 140 | 100 | 3 | ? |

Pada dataset tersebut terdapat **missing value pada atribut Harga untuk rumah R5**.

Kita akan memperkirakan nilai harga rumah R5 menggunakan metode **KNN**.

## Atribut yang Digunakan

Untuk memperkirakan harga rumah, atribut pembanding yang digunakan adalah:

- Luas Tanah
- Luas Bangunan
- Jumlah Kamar

## Contoh Perhitungan Euclidean Distance

Perhitungan jarak antara rumah **R5** dan **R1**.

$$
d = \sqrt{(140-120)^2 + (100-90)^2 + (3-3)^2}
$$

$$
d = \sqrt{400 + 100 + 0}
$$

$$
d = \sqrt{500} = 22.36
$$

Perhitungan yang sama dilakukan terhadap semua data rumah lainnya untuk menemukan tetangga yang paling mirip.

In [1]:
import pandas as pd

data = {
    'Rumah':['R1','R2','R3','R4'],
    'Luas_Tanah':[120,200,150,90],
    'Luas_Bangunan':[90,150,110,70],
    'Jumlah_Kamar':[3,4,3,2],
    'Harga':[850,1500,1000,600]
}

df = pd.DataFrame(data)
df

  Rumah  Luas_Tanah  Luas_Bangunan  Jumlah_Kamar  Harga
0    R1         120             90             3    850
1    R2         200            150             4   1500
2    R3         150            110             3   1000
3    R4          90             70             2    600

In [2]:
import numpy as np

target = np.array([140,100,3])

features = df[['Luas_Tanah','Luas_Bangunan','Jumlah_Kamar']].values

distances = np.sqrt(((features-target)**2).sum(axis=1))

df['Distance'] = distances

df.sort_values('Distance')

  Rumah  Luas_Tanah  Luas_Bangunan  Jumlah_Kamar  Harga   Distance
2    R3         150            110             3   1000  14.142136
0    R1         120             90             3    850  22.360680
3    R4          90             70             2    600  58.318093
1    R2         200            150             4   1500  78.108898

## Menentukan Nilai K

Misalkan dipilih **K = 3** tetangga terdekat.

In [3]:
k = 3

nearest = df.sort_values('Distance').head(k)

nearest

  Rumah  Luas_Tanah  Luas_Bangunan  Jumlah_Kamar  Harga   Distance
2    R3         150            110             3   1000  14.142136
0    R1         120             90             3    850  22.360680
3    R4          90             70             2    600  58.318093

## Menghitung Estimasi Harga

Nilai harga diperkirakan menggunakan rata-rata harga dari tetangga terdekat.

In [4]:
estimated_price = nearest['Harga'].mean()

estimated_price

np.float64(816.6666666666666)

## Kesimpulan

Dengan menggunakan metode **K-Nearest Neighbor**, nilai harga rumah R5 dapat diperkirakan berdasarkan rumah yang memiliki karakteristik paling mirip.

Metode ini bekerja dengan mencari tetangga terdekat berdasarkan **Euclidean Distance** kemudian menggunakan **rata-rata nilai dari tetangga tersebut**.

KNN merupakan metode yang sederhana namun cukup efektif untuk:

- klasifikasi
- regresi
- imputasi missing value